# Generated by Django 5.2.1 on 2025-05-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='foto_portada',
        ),
        migrations.AddField(
            model_name='libro',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='portadas_libros/'),
        ),
    ]
