# Generated by Django 5.2.1 on 2025-05-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_libro_foto_portada_libro_foto_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='descripcion',
            new_name='resumen',
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo_del_libro',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
