# Generated by Django 5.2.1 on 2025-05-16 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_descripcion_libro_resumen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foro',
            name='usuario',
        ),
        migrations.AddField(
            model_name='foro',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foros_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=False)),
                ('foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.foro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('foro', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='foro',
            name='participantes',
            field=models.ManyToManyField(related_name='foros_participando', through='main.Participacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
