# Generated by Django 5.2.1 on 2025-05-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_foro_usuario_foro_creador_participacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='libros_leidos',
            field=models.ManyToManyField(blank=True, related_name='usuarios_que_leyeron', to='main.libro'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='libros_por_leer',
            field=models.ManyToManyField(blank=True, related_name='usuarios_que_quieren_leer', to='main.libro'),
        ),
    ]
