# Generated by Django 5.2.1 on 2025-06-04 22:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_perfilusuario_libros_leidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
